# Generated by bin/relock. ruby-lsp composed bundle = main project gems
# plus the additions below. Identical entries are inherited from
# ../gemset.nix; only new or version-shifted gems appear here.
(import ../gemset.nix) // {
  rbs = {
    dependencies = ["logger" "prism" "tsort"];
    groups = ["default"];
    platforms = [];
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "09ggg2zk0qrh0mc3fa23xjbn2gzqxd0jfqj6qm6460ydcqg6fxdg";
      target = "ruby";
      type = "gem";
    };
    targets = [];
    version = "4.0.2";
  };
  ruby-lsp = {
    dependencies = ["language_server-protocol" "prism" "rbs"];
    groups = ["default"];
    platforms = [];
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "0aa1mg6bdl23wgrxd98wycq3963jfpnh9z0yh976p9q03h01r81k";
      target = "ruby";
      type = "gem";
    };
    targets = [];
    version = "0.26.9";
  };
  ruby-lsp-rails = {
    dependencies = ["ruby-lsp"];
    groups = ["default"];
    platforms = [];
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "1bj4bj35l9jas2yf6w93j5ngw3f24lck2j9h5zmxwqs0dn91z7gh";
      target = "ruby";
      type = "gem";
    };
    targets = [];
    version = "0.4.8";
  };
}
