# Generated by nix/relock. ruby-lsp composed bundle = main project gems
# plus the additions below. Identical entries are inherited from
# ../gemset.nix; only new or version-shifted gems appear here.
(import ../gemset.nix) // {
  ruby-lsp = {
    dependencies = ["language_server-protocol" "prism" "rbs"];
    groups = ["default"];
    platforms = [];
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "1vdv4dydl0xsqbqq6c6r9mm5l6s2jq2kb0x5p7v32da2jjpq8wp6";
      target = "ruby";
      type = "gem";
    };
    targets = [];
    version = "0.26.10";
  };
  ruby-lsp-rails = {
    dependencies = ["ruby-lsp"];
    groups = ["default"];
    platforms = [];
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "1bj4bj35l9jas2yf6w93j5ngw3f24lck2j9h5zmxwqs0dn91z7gh";
      target = "ruby";
      type = "gem";
    };
    targets = [];
    version = "0.4.8";
  };
}
